version: '3'

services:
  mysql:
    image: mysql:9.0
    container_name: to_do_list2_mysql
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306